server:
  port: 9002



spring:
  application:
    name: CATEGORY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9006/eureka/
    instance: localhost